"""empty message

Revision ID: 05f5b7edc036
Revises: c48e37b9b987
Create Date: 2017-08-03 16:20:03.251552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f5b7edc036'
down_revision = 'c48e37b9b987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'Attachment')
    op.add_column('users', sa.Column('Company', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Company')
    op.add_column('materials', sa.Column('Attachment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
