"""empty message

Revision ID: 387f057afe9a
Revises: 
Create Date: 2017-08-03 13:01:39.473261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387f057afe9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workorder', sa.Column('Attachment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workorder', 'Attachment')
    # ### end Alembic commands ###
