"""empty message

Revision ID: 4b01e6205b43
Revises: 05f5b7edc036
Create Date: 2017-08-03 16:23:12.644428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b01e6205b43'
down_revision = '05f5b7edc036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('Attachment', sa.String(length=100), nullable=True))
    op.drop_column('users', 'Company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Company', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('materials', 'Attachment')
    # ### end Alembic commands ###
