"""empty message

Revision ID: 59004537872e
Revises: 4b01e6205b43
Create Date: 2017-08-08 22:13:32.599222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59004537872e'
down_revision = '4b01e6205b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=50), nullable=True),
    sa.Column('File Location', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'link_table', sa.Column('attachments_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link_table', 'attachments', ['attachments_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link_table', type_='foreignkey')
    op.drop_column(u'link_table', 'attachments_id')
    op.drop_table('attachments')
    # ### end Alembic commands ###
