"""empty message

Revision ID: f05a3592fed0
Revises: 59004537872e
Create Date: 2017-08-23 13:53:29.467800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05a3592fed0'
down_revision = '59004537872e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hours', sa.Column('1.5 x OT Hours', sa.Integer(), nullable=True))
    op.add_column('hours', sa.Column('2.0 x OT Hours', sa.Integer(), nullable=True))
    op.drop_column('hours', 'Hourly Rate')
    op.drop_column('hours', 'Overtime Hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hours', sa.Column('Overtime Hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hours', sa.Column('Hourly Rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('hours', '2.0 x OT Hours')
    op.drop_column('hours', '1.5 x OT Hours')
    # ### end Alembic commands ###
